### ISSUE TITLE
[no issue] - just kudos and question

### ISSUE THREAD

**Issue by GreyEarl** [horvathgergo/uPurifier#1]
Hi! Sorry to misuse this, but just wanted to say I'm very excited with this project. I have ordered the PCB's and should arrive any time soon. After that I will use and test your uPurifier firmware. Can't wait! Are you open for donations?

Also, can you share details on what Lovelace element/card you are using?
![image](https://user-images.githubusercontent.com/33351068/230029296-a7e9a170-2c30-4d20-90eb-91c069d81350.png)

**Comment by horvathgergo** [comment]
> Hi! Sorry to misuse this, but just wanted to say I'm very excited with this project. I have ordered the PCB's and should arrive any time soon. After that I will use and test your uPurifier firmware. Can't wait! Are you open for donations?
> 
> 
> 
> Also, can you share details on what Lovelace element/card you are using?
> 
> ![image](https://user-images.githubusercontent.com/33351068/230029296-a7e9a170-2c30-4d20-90eb-91c069d81350.png)
> 
> 

Thanks for your interest. I hope you will like it. On my lovelace i use mushroom and manually created cards for the purifiers but to be honest the newly introduced changes to HA frontend (2023.04 i believe) are way more appealing for me in terms of UI experience. So, i may change to that soon.

HA new fan card:
![image](https://user-images.githubusercontent.com/44551566/232209867-94bdd42a-9b6c-45a5-8467-3ecf5b921f13.jpeg)

As for donations, i placed a link on the bottom the the project descriptions of each purifiers that let anyone to contribute to the cost of development with 1$.

**Comment by GreyEarl** [comment]
Great! Thanks for your reply! Do you have PayPal by any chance? I can't use the buymeacoffee service due to lack of creditcard.
