### ISSUE TITLE
Not connecting to WiFi

### ISSUE THREAD

**Issue by GreyEarl** [horvathgergo/uPurifier#2]
I'm stuck with the last step, which is connecting to my home network. I submitted my WiFi name, credentials, MQTT server IP etc. I see the entered data also stored on the ESP in config.json and the initial AP is disabled. However, the board is not connecting to my home network. I don't see the device popping up in my device list in my router.

I made sure the network is 2,4Ghz and I'm very close to the router.

Not sure where it goes wrong. Any idea? I don't have an MQTT username and password, so I left it blank.

**Comment by horvathgergo** [comment]
> I'm stuck with the last step, which is connecting to my home network. I submitted my WiFi name, credentials, MQTT server IP etc. I see the entered data also stored on the ESP in config.json and the initial AP is disabled. However, the board is not connecting to my home network. I don't see the device popping up in my device list in my router.
> 
> 
> 
> I made sure the network is 2,4Ghz and I'm very close to the router.
> 
> 
> 
> Not sure where it goes wrong. Any idea? I don't have an MQTT username and password, so I left it blank.

Have you tried unplug and plug it again? I let it 4 sec to connect before opening the captive portal but maybe it's not enough in your case

**Comment by GreyEarl** [comment]
Yes, multiple times I disconnected and reconnected with delay. Do you perhaps have a ready-to-go BIN file I could flash? What I did now is to directly flash MicroPython and manually copied your files to the board. Maybe something went bad there.

So, do let me know if you have an BIN I can try.

**Comment by horvathgergo** [comment]
Unfortunately i haven't created the bin, but now i think it may stuck at mqtt as the code doesn't handle connecting without credentials (mqtt expects None instead of an empty string). I'm going to add this option and upload the code again

**Comment by GreyEarl** [comment]
> Unfortunately i haven't created the bin, but now i think it may stuck at mqtt as the code doesn't handle connecting without credentials (mqtt expects None instead of an empty string). I'm going to add this option and upload the code again

Would it be the same as changing the empty strings in config.json to 'None'? Or am I too simple minded?
Just to double check the following:

The files in your firmware folder needs to be copied to the root of the ESP, correct?
Also overiding the original boot.py completely, also correct?

**Edit;**
I just tried with a new temp MQTT instance with password/username enabled. Unfortuntaly same result. The board is not connecting to my network. Now it also seems the default AP is still active, every time I submit, disconnect, connect. However, the config.json is created.

**Comment by GreyEarl** [comment]
@horvathgergo is it possible to share the full code in readable text rather in binary format (mpy)?

**Comment by horvathgergo** [comment]
You can find the code uploaded in the root (called upurifier.py)

**Comment by GreyEarl** [comment]
> You can find the code uploaded in the root (called upurifier.py)

Oh sorry, didnt notice it all, thanks! Breaking my head over this for a few days now trying to get it to work.

**Comment by GreyEarl** [comment]
I ended up using esphome instead. In the process I think it could  have interferred with (one of) below reasons.

MQTT no auth support. It occured me that I did not tested wheter my test MQTT instance with username/password was reachable in my network. Only tested locally.

No sufficient power during WiFi pairing.

I might test it later on with a different board.

**Comment by horvathgergo** [comment]
Thanks for testing, i'm also trying to investigate the root cause

**Comment by AvinPang** [comment]
I noticed that it doesn´t connect to WiFi if you use Micropython v1.20.0. It connect for me when i switch it to Micropython v1.19.1.
However i still did not manage to get the device to show up on my home assistant after it is connected to WiFi.

**Comment by horvathgergo** [comment]
Don't you see it under mosquitto broker? Could you provide me with the version number of HA and Mosquitto that you currently use?

**Comment by horvathgergo** [comment]
> I noticed that it doesn´t connect to WiFi if you use Micropython v1.20.0. It connect for me when i switch it to Micropython v1.19.1.
> 
> However i still did not manage to get the device to show up on my home assistant after it is connected to WiFi.

I'm not aware (yet) of any changes in Micropython 1.20 that causes wifi issues but i believe Mosquitto 6.2 may reject mqtt connection due to changes in handling of keepalive parameter.

**Comment by AvinPang** [comment]
> 
I am on HA 2023.5.2 and Mosquitto broker 6.2.1.
I will try later today to revert back to Mosquitto broker 6.1.3 to see if it makes any difference.

**Comment by dilipva** [comment]
Even after the device is connected to wifi, ap mode is still active. MQTT connection failed with the following messages in log.

`1684256850: New connection from 192.168.0.49:8961 on port 1883.
1684256850: New client connected from 192.168.0.49:8961 as 08a18300 (p2, c1, k0, u'homeassistant').
1684256850: Bad socket read/write on client 08a18300: Invalid arguments provided.`

**Comment by horvathgergo** [comment]
> Even after the device is connected to wifi, ap mode is still active. MQTT connection failed with the following messages in log.
> 
> 
> 
> `1684256850: New connection from 192.168.0.49:8961 on port 1883.
> 
> 1684256850: New client connected from 192.168.0.49:8961 as 08a18300 (p2, c1, k0, u'homeassistant').
> 
> 1684256850: Bad socket read/write on client 08a18300: Invalid arguments provided.`

If mqtt fails to connect then ap gets activated. What is your mosquitto version?

**Comment by dilipva** [comment]
it's mosquitto version 2.0.15

**Comment by horvathgergo** [comment]
@dilipva @AvinPang  @GreyEarl I believe I fixed all the connection issues and uploaded the new source code (upurifier.mpy v.0.1.2-beta) so if you have a chance please test it

**Comment by AvinPang** [comment]
> @dilipva @AvinPang @GreyEarl I believe I fixed all the connection issues and uploaded the new source code (upurifier.mpy v.0.1.2-beta) so if you have a chance please test it

I have been testing this whole morning. This new version seems to work.
What i found is that i was able to connect using my HA administrator user.
I then created a separate user without administrator right and that did not work, once i give the user administrator rights then it works.

![image](https://github.com/horvathgergo/uPurifier/assets/35901712/c8c1230b-9a50-4e5f-bf22-4f7786343e70)

It soon become unavailable again but i guess that is because i have not yet plugged in the board to the air purifier. Time to plug it in now :)

**Comment by lukasmalkmus** [comment]
@GreyEarl Do you mind sharing the ESPHome config? You put ESPHome onto the custom boards for this project, right? I'm trying to debug some issues described in #5 and with that config I could try to rule out a hardware malfunction. Cheers!

**Comment by GreyEarl** [comment]
@lukasmalkmus Sure, here is my ESPHome config:

```
output:
  - platform: esp8266_pwm
    pin: 5
    frequency: 150 Hz
    id: pwm_output
    min_power: 0.5
    max_power: 0.5
    zero_means_zero: true

fan:
  - platform: speed
    output: pwm_output
    name: "Fornuftig Air Purifier"
    id: "fornuftig_fan"
    restore_mode: RESTORE_DEFAULT_OFF
    on_speed_set:
      lambda: |-
        if(id(fornuftig_fan).speed != id(fan_speed) && id(fornuftig_fan).state){
          id(fan_speed) = id(fornuftig_fan).speed;
          id(set_fan_freq).publish_state(id(fornuftig_fan).speed);
        }
    on_turn_on:
      lambda: |-
       id(set_fan_freq).publish_state(id(fornuftig_fan).speed);
    on_turn_off:
      - output.esp8266_pwm.set_frequency:
          id: pwm_output
          frequency: !lambda 'return int(0);'
      - logger.log: "Fan Turned Off!"

sensor:
  - platform: pulse_counter
    pin: 
      number: 4
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    id: fan_tach
    name: Fornuftig Fanspeed
    filters:
      - multiply: 0.1

  - platform: template
    id: set_fan_freq
    filters:
      - multiply: 3
      - lambda: |-
          if (id(fornuftig_fan).state){
            if(x > 300) { // limit max frequency
              return 300;
              
            } else if(x < 36 && x > 3) { // limit low frequency
              return 36;
              
            } else if(x <= 3) {
              return 0;
              
            } else {
              return x;
              
            }
          } else {
            return 0;
          }
    on_value:
      then:
        - output.esp8266_pwm.set_frequency:
            id: pwm_output
            frequency: !lambda 'return int(x);'
        - logger.log: "on_value called"
        - lambda: |- 
            // send current status to homeassistant
            if(x) {
              auto call = id(fornuftig_fan).turn_on();
              call.set_speed(int(x)/3);
              call.perform();
            } else {
              auto call = id(fornuftig_fan).turn_off();
              call.perform();
            }

binary_sensor:
  - platform: template
    id: 'knob_0'
    filters:
      - delayed_on_off: 300ms
    lambda: |-
      if (!id(knob_1).state && !id(knob_2).state && !id(knob_3).state) {
        return true;
      } else {
        return false;
      }
    on_press: 
      lambda: |-
        if(!id(speed_0)){
          auto call = id(fornuftig_fan).turn_off();
          call.perform();
        }else{
          auto call = id(fornuftig_fan).turn_on();
          call.set_speed(id(speed_0));
          call.perform();
        }

  - platform: gpio
    id: 'knob_1'
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 100ms
    on_press: 
      then:
        - fan.turn_on:
            id: fornuftig_fan
            speed: !lambda 'return id(speed_1);'
    
    
  - platform: gpio
    id: 'knob_2'
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 100ms
    on_press: 
      then:
        - fan.turn_on:
            id: fornuftig_fan
            speed: !lambda 'return id(speed_2);'
  
  
  - platform: gpio
    id: 'knob_3'
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - fan.turn_on:
            id: fornuftig_fan
            speed: !lambda 'return id(speed_3);'

globals:
  - id: fan_speed
    type: int
    restore_value: yes
    initial_value: '0'
    
  - id: speed_0
    type: int
    restore_value: yes
    initial_value: '0'
    
  - id: speed_1
    type: int
    restore_value: yes
    initial_value: '33'
    
  - id: speed_2
    type: int
    restore_value: yes
    initial_value: '66'
    
  - id: speed_3
    type: int
    restore_value: yes
    initial_value: '100'
```
