### ISSUE TITLE
Unable to open captive portal

### ISSUE THREAD

**Issue by AvinPang** [horvathgergo/uPurifier#4]
Hi, i have assembled 2 board, flash with microPython and uploaded all files in firmware to root of the device and overwritten boot.py. 
i am able to see the micropython AP and it accepted the password but captive portal is not opening. I also tried http://192.168.4.1/ without success. I have also tried the reset button and inplug it for awhile. Is there anything that i am missing? I have only tried to connect from my iphone. I have not yet try from PC.

**Comment by horvathgergo** [comment]
Please try 192.168.4.2 as well

**Comment by AvinPang** [comment]
It doesn´t seems to work either... tried on PC now also, same issue.

**Comment by AvinPang** [comment]
Nevermind, i got it to work now. Turns out i accidently saved the style.css as style.htm instead. Great work :)
